spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
