package az.ingress.model.enums;

public enum OrderStatus {

    PENDING,

    PRODUCT_CHECK_PENDING,
    PRODUCT_CHECK_SUCCESS,
    PRODUCT_CHECK_FAILED,
    PRODUCT_FAILED,
    PRODUCT_RESERVATION_FAILED,
    PRODUCT_RESERVATION_COMPLETED,

    PAYMENT_PENDING,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,

    PLACED,
    SHIPPED,
    DELIVERED,
    CANCELLED,
    RETURNED
}
