package az.ingress.model.enums;

public enum PaymentErrorType {
    INSUFFICIENT_BALANCE,
    AMOUNT_EXCEEDS_LIMIT,
    INVALID_METHOD,
    CARD_EXPIRED,
    INVALID_CARD_DETAILS,
    PAYMENT_GATEWAY_ERROR,
    PAYMENT_TIMEOUT,
    PAYMENT_DECLINED,
    CURRENCY_NOT_SUPPORTED,
    TRANSACTION_LIMIT_EXCEEDED,
    FRAUD_DETECTED,
    REFUND_FAILED
}
